"use client";

import {
  AlertTriangle,
  CheckCircle2,
  ArrowRight,
} from "lucide-react";

import { simulationResults } from "@/data/simulations";

export default function SimulationResults() {
  return (
    <section className="simulation-results-card">
      <div className="simulation-card-header">
        <div>
          <span className="section-eyebrow">
            SIMULATION OUTPUT
          </span>

          <h2>Recommended response</h2>

          <p>
            Operational changes generated by the simulation.
          </p>
        </div>
      </div>

      <div className="simulation-results">
        {simulationResults.map((result) => (
          <div
            className="simulation-result"
            key={result.label}
          >
            <div className="simulation-result-icon">
              {result.status === "BLOCKED" ? (
                <AlertTriangle size={17} />
              ) : (
                <CheckCircle2 size={17} />
              )}
            </div>

            <div className="simulation-result-content">
              <span>{result.label}</span>
              <strong>{result.value}</strong>
            </div>

            <span
              className={`simulation-result-status status-${result.status.toLowerCase()}`}
            >
              {result.status}
            </span>
          </div>
        ))}
      </div>

      <button
        type="button"
        className="simulation-apply-button"
      >
        Apply rerouting strategy
        <ArrowRight size={16} />
      </button>
    </section>
  );
}